define robot_group11 position
(
      size [1 0.75 0.75]

      # the shape of robot_group11
      
          block
      (
            points 8
            point[7] [0.25 0.1]
            point[6] [0 0.35]
            point[5] [0 0.85]
            point[4] [0.25 1.1]
            point[3] [0.75 1.1]
            point[2] [1 0.85]
            point[1] [1 0.35]
            point[0] [0.75 0.1]
            z [0 1]
      )

      block
      (
            points 4
            point[3] [0.375 1.2]
            point[2] [0.625 1.2]
            point[1] [0.625 1.1]
            point[0] [0.375 1.1]
            z [0 0.25]
      )

      block
      (
            points 4
            point[3] [0.375 0.1]
            point[2] [0.625 0.1]
            point[1] [0.625 0]
            point[0] [0.375 0]
            z [0 0.25]
      )

)


